//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBDiscordAssistant.DiscordBot.DiscordNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBDiscordAssistant.DiscordBot.DiscordNet.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} added to team &apos;{1}&apos;..
        /// </summary>
        public static string AddPlayerSuccessful {
            get {
                return ResourceManager.GetString("AddPlayerSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added tournament director to tournament &apos;{0}&apos; in guild &apos;{1}&apos;..
        /// </summary>
        public static string AddTournamentDirectorSuccessful {
            get {
                return ResourceManager.GetString("AddTournamentDirectorSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All possible tournament artifacts cleaned up in guild &apos;{0}&apos;..
        /// </summary>
        public static string AllPossibleTournamentArtifactsCleaned {
            get {
                return ResourceManager.GetString("AllPossibleTournamentArtifactsCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reader names should be unique..
        /// </summary>
        public static string AllReaderNamesShouldBeUnique {
            get {
                return ResourceManager.GetString("AllReaderNamesShouldBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go back from the stage {0}..
        /// </summary>
        public static string CannotGoBack {
            get {
                return ResourceManager.GetString("CannotGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can only be used when a tournament is ready to start, which is after all the players have joined their teams..
        /// </summary>
        public static string CommandOnlyUsedTournamentReadyStart {
            get {
                return ResourceManager.GetString("CommandOnlyUsedTournamentReadyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can only be used while the tournament is running. Use !back if you are still setting up the tournament..
        /// </summary>
        public static string CommandOnlyUsedWhileTournamentRunning {
            get {
                return ResourceManager.GetString("CommandOnlyUsedWhileTournamentRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the role for the old reader. Readers were not switched. You may need to manually switch the roles..
        /// </summary>
        public static string CouldntGetRoleForTheOldReader {
            get {
                return ResourceManager.GetString("CouldntGetRoleForTheOldReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the channels and roles....
        /// </summary>
        public static string CreatingChannelsAndRoles {
            get {
                return ResourceManager.GetString("CreatingChannelsAndRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tournament in guild &apos;{0}&apos;: {1}.
        /// </summary>
        public static string CurrentTournamentInGuild {
            get {
                return ResourceManager.GetString("CurrentTournamentInGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: At least one team specified is not in the tournament. Teams specified: {0}..
        /// </summary>
        public static string ErrorAtLeastOneTeamNotInTournament {
            get {
                return ResourceManager.GetString("ErrorAtLeastOneTeamNotInTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: finals can only be set during the prelims..
        /// </summary>
        public static string ErrorFinalsOnlySetDuringPrelims {
            get {
                return ResourceManager.GetString("ErrorFinalsOnlySetDuringPrelims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorGenericMessage {
            get {
                return ResourceManager.GetString("ErrorGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: given user isn&apos;t a reader..
        /// </summary>
        public static string ErrorGivenUserIsntAReader {
            get {
                return ResourceManager.GetString("ErrorGivenUserIsntAReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No teams specified..
        /// </summary>
        public static string ErrorNoTeamsSpecified {
            get {
                return ResourceManager.GetString("ErrorNoTeamsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting the current tournament in guild &apos;{0}&apos;. {1}.
        /// </summary>
        public static string ErrorSettingCurrentTournament {
            get {
                return ResourceManager.GetString("ErrorSettingCurrentTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: two teams must be specified in the finals. You have specified {0}..
        /// </summary>
        public static string ErrorTwoTeamsMustBeSpecifiedFinals {
            get {
                return ResourceManager.GetString("ErrorTwoTeamsMustBeSpecifiedFinals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finals participants: please join the room {0} and join the voice channel for that room number..
        /// </summary>
        public static string FinalsParticipantsPleaseJoin {
            get {
                return ResourceManager.GetString("FinalsParticipantsPleaseJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a reader. The new reader must not be an existing reader..
        /// </summary>
        public static string IsAlreadyReader {
            get {
                return ResourceManager.GetString("IsAlreadyReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a current reader. You can only replace existing readers..
        /// </summary>
        public static string NotACurrentReader {
            get {
                return ResourceManager.GetString("NotACurrentReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teams have been created yet..
        /// </summary>
        public static string NoTeamsYet {
            get {
                return ResourceManager.GetString("NoTeamsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} is already on a team..
        /// </summary>
        public static string PlayerIsAlreadyOnTeam {
            get {
                return ResourceManager.GetString("PlayerIsAlreadyOnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} is not on any team..
        /// </summary>
        public static string PlayerIsNotOnAnyTeam {
            get {
                return ResourceManager.GetString("PlayerIsNotOnAnyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} removed..
        /// </summary>
        public static string PlayerRemoved {
            get {
                return ResourceManager.GetString("PlayerRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readers switched successfully..
        /// </summary>
        public static string ReadersSwitchedSuccessfully {
            get {
                return ResourceManager.GetString("ReadersSwitchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed tournament director from tournament &apos;{0}&apos; in guild &apos;{1}&apos;..
        /// </summary>
        public static string RemovedTournamentDirector {
            get {
                return ResourceManager.GetString("RemovedTournamentDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team &apos;{0}&apos; does not exist..
        /// </summary>
        public static string TeamDoesNotExist {
            get {
                return ResourceManager.GetString("TeamDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament cleanup finished in guild &apos;{0}&apos;..
        /// </summary>
        public static string TournamentCleanupFinished {
            get {
                return ResourceManager.GetString("TournamentCleanupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament &apos;{0}&apos; does not exist..
        /// </summary>
        public static string TournamentDoesNotExist {
            get {
                return ResourceManager.GetString("TournamentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: tournament has started..
        /// </summary>
        public static string TournamentHasStarted {
            get {
                return ResourceManager.GetString("TournamentHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament was not removed from the list of pending tournaments. Try the command again..
        /// </summary>
        public static string TournamentWasNotRemoved {
            get {
                return ResourceManager.GetString("TournamentWasNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform command. {0}.
        /// </summary>
        public static string UnableToPerformCommand {
            get {
                return ResourceManager.GetString("UnableToPerformCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error when trying to remove the old reader..
        /// </summary>
        public static string UnknownErrorRemovingOldReader {
            get {
                return ResourceManager.GetString("UnknownErrorRemovingOldReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already a director of &apos;{0}&apos; in guild &apos;{1}&apos;..
        /// </summary>
        public static string UserAlreadyTournamentDirector {
            get {
                return ResourceManager.GetString("UserAlreadyTournamentDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a director for tournament &apos;{0}&apos; in guild &apos;{1}&apos;, or user was just removed..
        /// </summary>
        public static string UserNotTournamentDirector {
            get {
                return ResourceManager.GetString("UserNotTournamentDirector", resourceCulture);
            }
        }
    }
}
